name: Datadog Auto Scaling

on:
  repository_dispatch:
    types: [scale_up, scale_down]

jobs:
  autoscale:
    runs-on: ubuntu-latest
    env:
      TF_VAR_max_instance_count: ${{ github.event.client_payload.max_instance_count }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
