name: Deploy Infra and Datadog Monitor

on:
  push:
    branches:
      - stg  

jobs:
  terraform:
    name: 'Deploy Infra and Datadog Monitors'
    runs-on: ubuntu-latest

    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Enable Terraform Debug Logs
        run: echo "TF_LOG=DEBUG" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ./envs/stg
        run: terraform init
      
      - name: Terraform Validate
        working-directory: ./envs/stg
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./envs/stg
        run: terraform plan  
        timeout-minutes: 8

      - name: Terraform Apply
        working-directory: ./envs/stg
        run: terraform apply -auto-approve
